#!/usr/bin/python3

import os, sys
import shutil
import subprocess
import copy
import io
import json
import tempfile
import argparse
import time
from datetime import datetime
from zipfile import ZipFile

from pymlutil.jsonutil import cmd, ReadDict, WriteDict
from torchdatasetutil.version import VersionString

def parse_arguments():
    parser = argparse.ArgumentParser(description='Process arguments')

    parser.add_argument('--debug','-d', action='store_true',help='Wait for debuggee attach')   
    parser.add_argument('-debug_port', type=int, default=3300, help='Debug port')
    parser.add_argument('-debug_listen', type=str, default='0.0.0.0', help='Default, accept any client')

    parser.add_argument('-credentails', type=str, default='creds.yaml', help='Credentials file')
    parser.add_argument('-package', type=str, default='torchdatasetutil', help='Credentials key')
    parser.add_argument('-config', type=str, default='torchdatasetutil/build.yaml', help='Configuration file')
    parser.add_argument('-password', type=str, default=None, help='Output path')
    parser.add_argument('--message', '-m', type=str, default=None, help='Version get message')
    parser.add_argument('--test', '-t', action='store_true', help='Test deploy')

    args = parser.parse_args()
    return args

def Archive(args, config):
    result = 0
    config['version']['patch'] += 1
    version_str = VersionString(config)
    WriteDict(config, args.config)

    cmdstr = 'git add {}'.format(args.config)
    cmd(cmdstr)

    cmdstr = 'git commit -m "Tag version {}"'.format(version_str)
    cmd(cmdstr)

    cmdstr = 'git diff-index --quiet HEAD --;'
    result, stderr, stdout = cmd(cmdstr, check=False)
    if result != 0 and not args.test:
        print ('Changes in working tree.  Please commit before creating a versioned repository.  Run "git status" for more information.')
        return result, config, version_str
    else:
        result=0
    
    if args.message is None:
        description = "{} version {}".format(config['name'], version_str)
    else:
        description = args.description
    cmdstr = 'git tag -a {} -m "{}"'.format(version_str,description )
    cmd(cmdstr)

    cmdstr = 'git push origin {}'.format(version_str)
    cmd(cmdstr)

    cmdstr = 'git push'
    cmd(cmdstr)
    
    return result, config, version_str

def main(args):
    initial = datetime.now()

    creds = ReadDict(args.credentails)
    config = ReadDict(args.config)

    cmdstr = "python3 -m unittest discover"
    cmd(cmdstr)

    result, config, version_str = Archive(args, config)
    if result:
        return result

    print("Create {} version: {}".format(config['name'],version_str))

    pwd = os.getcwd()

    shutil.rmtree('dist/', ignore_errors=True)
    os.mkdir('dist/')

    cmdstr = "python3 setup.py sdist bdist_wheel"
    cmd(cmdstr)

    pipy_creds = next(filter(lambda d: d.get('package') == args.package, creds['pipy']), None)
    cmdstr = "twine upload dist/* -u {} -p {}".format(pipy_creds['username'], pipy_creds['password'])
    cmd(cmdstr)

    is_new_version_loaded = False
    while not is_new_version_loaded:
        time.sleep(5)
        cmdstr = "pip3 install --upgrade {}".format(config['name'])
        cmd(cmdstr)

        cmdstr = 'python3 -c "import sys; from {}.version import __version__; sys.exit(__version__)"'.format(config['name'])
        _, loaded_version, _ = cmd(cmdstr, check=False, capture_output=True)
        loaded_str = loaded_version.decode("utf-8").replace("\n", "")
        if loaded_str==version_str:
            is_new_version_loaded = True

    dt = (datetime.now()-initial).total_seconds()
    print("Setup version {} complete {}s".format(config['version'], dt))
    return result


if __name__ == '__main__':
    import argparse
    args = parse_arguments()

    if args.debug:
        print("Wait for debugger attach")
        import debugpy
        debugpy.listen(address=(args.debug_listen, args.debug_port))
        debugpy.wait_for_client() # Pause the program until a remote debugger is attached
        print("Debugger attached")

    result = main(args)
    sys.exit(result)