coco:
  credentials: 'creds.yaml'
  dataset_train: 'data/coco/annotations/instances_train2017.json'
  dataset_val: 'data/coco/annotations/instances_val2017.json'
  train_image_path: 'data/coco/train2017'
  val_image_path: 'data/coco/val2017'
  class_dict: 'model/segmin/coco.json'
  test_images: null
  num_workers: 0
  batch_size: 2

images:
  credentials: 'creds.yaml'
  dataset: 'annotations/lit/dataset.yaml'
  class_dict: 'model/crisplit/lit.json'
  test_images: 10