coco:
  credentials: 'creds.yaml'
  dataset_train: 'data/coco/annotations/instances_train2017.json'
  dataset_val: 'data/coco/annotations/instances_val2017.json'
  train_image_path: 'data/coco/train2017'
  val_image_path: 'data/coco/val2017'
  class_dict: 'model/segmin/coco.json'
  test_images: 10
  num_workers: 1
  batch_size: 4
  height: 640
  width: 480

images:
  credentials: 'creds.yaml'
  dataset: 'data/lit/dataset.yaml'
  class_dict: 'model/crisplit/lit.json'
  test_images: 10
  num_workers: 1
  batch_size: 4
  height: 480 
  width: 640

cityscapes:
  credentials: creds.yaml
  obj_src: data/cityscapes
  destination: /nvmestore/mlstore/mllib/data/cityscapes
  class_dict: model/cityscapes/cityscapesfull.json
  test_path: test/cityscapes
  test_images: 10
  num_workers: 0
  batch_size: 2
  height: 512
  width: 768
  sampler: True

imagenet:
  credentials: creds.yaml
  obj_src: data/cityscapes
  destination: /nvmestore/mlstore/mllib/data/imagenet
  test_path: test/imagenenet
  test_images: 10
  num_workers: 0
  batch_size: 2
  height: 512
  width: 768
  flipX: True 
  flipY: False
  rotate: 3
  scale_min: 0.75
  scale_max: 1.25 
  offset: 0.1
  augment_noise: 0.1

cifar10:
  test_path: test/cifar10
  test_images: 10
